# Generated by Django 5.1.4 on 2025-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_name_dailyactivityreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivityreport',
            name='task',
            field=models.CharField(default='No task assigned', max_length=255),
        ),
    ]
