# Generated by Django 5.1.4 on 2025-01-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dailyactivityreport_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
